baseURL = "https://www.rantswithal.com/"
languageCode = "en-gb"
title = "Rants With Al"
theme = "hyde"

[params]
  themeColor = "theme-base-0b"
  layoutReverse = true
  description = "A short podcast about what frustrates Al"
  creator = "TheScotBot"
  author = "Al McKinlay"
  pocketcasts = "https://pca.st/ooTG"
  spotify = "https://open.spotify.com/show/2JiDXfpNBYcsJVUfAzlN55"