baseURL = "https://www.rantswithal.com/"
languageCode = "en-gb"
title = "Rants With Al"
theme = "hyde"

[params]
  themeColor = "theme-base-0b"
  layoutReverse = true
  description = "A short podcast about what frustrates Al"
  creator = "TheScotBot"